"""empty message

Revision ID: 0d14e41acb32
Revises: e58db208aaed
Create Date: 2019-03-02 14:03:47.335701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d14e41acb32'
down_revision = 'e58db208aaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companyHasproperty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.INTEGER(), nullable=False),
    sa.Column('p_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['p_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companyHasproperty')
    op.drop_table('property')
    op.drop_table('company')
    # ### end Alembic commands ###
