"""empty message

Revision ID: b421c0624749
Revises: 0d14e41acb32
Create Date: 2019-03-03 14:27:12.556382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b421c0624749'
down_revision = '0d14e41acb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('category', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'category')
    # ### end Alembic commands ###
